### ISSUE TITLE
代码块行号的高度

### ISSUE THREAD

**Issue by frostime** [frostime/sy-line-height#1]

**Comment by TCOTC** [comment]
确实对不齐，有办法改进吗？

![image](https://github.com/frostime/sy-line-height/assets/78434827/f45f3c81-5638-4603-b91d-4694e4161cbc)

**Comment by frostime** [comment]
> 确实对不齐，有办法改进吗？
> 
> ![image](https://private-user-images.githubusercontent.com/78434827/329479985-f45f3c81-5638-4603-b91d-4694e4161cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjI2MjgsIm5iZiI6MTcxNTMyMjMyOCwicGF0aCI6Ii83ODQzNDgyNy8zMjk0Nzk5ODUtZjQ1ZjNjODEtNTYzOC00NjAzLWI5MWQtNDY5NGU0MTYxY2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2MjUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzZTgxMzhmMzdlYTgwMGQ4MDcxNzhhYjlmYWZmMjRkNTkxNDg2YzdlNjdjNjNlMmE1MzgwN2UxZjdjODcyYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qaFULEA_u-DDzLc9HsQNR0zKwc0q_ndrkAK5su3gJgU)

哦，因为我代码块从来不开行号，所以这个问题一直没管。

行号的 dom 结构不是文本框，他和代码的对齐是基于 padding、height 等样式来实现的，稍微麻烦一点。

我有空看看怎么处理吧。（主要是我也很少用这个插件）
