### ISSUE TITLE
不显示不兼容，但不生效

### ISSUE THREAD

**Issue by xzajyjs** [frostime/sy-line-height#6]
docker和客户端版都试了，旧版本和最新版都试了，可以打上勾，但是关掉设置就自动取消了，并未生效
![Snipaste_2024-10-12_11-13-14](https://github.com/user-attachments/assets/28f6eeaa-eb7a-47f5-a7fe-e715a9dbde34)

**Comment by xzajyjs** [comment]
找到原因了，plugin name需要和文件夹名相同，建议release中的package解压后的文件夹名改为`sy-line-height`

**Comment by frostime** [comment]
release 里面的 package.zip 是给思源的自动 action 程序读取的，乱改里面的格式存在一定风险，可能会让集市程序没法正常读取。
